# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Everett's Projects
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://everettsprojects.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  evjrob

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

theme: minima
plugins:
  - jekyll-feed

# Ideal image slider
iis_slider_array: []

# Leave shortname blank to disable comments site-wide.
# Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
disqus:
  shortname: everettsprojects

# Google Analytics
google_analytics: UA-51737914-1

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
