# Site settings
title: Everett's Projects
email: evjrob@gmail.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://everettsprojects.com" # the base hostname & protocol for your site
github_username:  evjrob
linkedin: everett-robinson-19823849

# Build settings
markdown: kramdown

highlighter: rouge

# Ideal image slider
iis_slider_array: []

# Leave shortname blank to disable comments site-wide.
# Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
disqus:
  shortname: everettsprojects

# Google Analytics
google_analytics: UA-51737914-1

# Pagination
#paginate: 15
#paginate_path: "/page:num/"

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
