version: 0.2

phases:
  install:
    runtime-versions:
        ruby: 2.7
        python: 3.7
    commands:
      - pip install cfn-lint
      - gem install bundler
      - bundle install
  pre_build:
    commands:
      - cfn-lint -t _deploy/sam-app/template.yaml
  build:
    commands:
      - JEKYLL_ENV=production bundle exec jekyll build
      - cd _deploy/sam-app/
      - sam build
  post_build:
    commands:
      - sam package --s3-bucket ${PACKAGE_BUCKET} --output-template-file packaged-template.yaml
      - cd ../..
      - cp _deploy/sam-app/packaged-template.yaml packaged-template.yaml
artifacts:
  secondary-artifacts:
    SAMArtifacts:
      files:
        - packaged-template.yaml
    BlogArtifacts:
      files:
        - '**/*'
      base-directory: _site
    